# Generated by Django 4.0.4 on 2023-07-23 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cargaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('bac', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bacsApp.bac')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=30)),
                ('furnisseur', models.BooleanField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('bac', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bacsApp.bac')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bacsApp.site')),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='bac',
            field=models.ManyToManyField(null=True, through='bacsApp.Stock', to='bacsApp.bac'),
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('retour', models.CharField(max_length=30)),
                ('livraison', models.ManyToManyField(null=True, through='bacsApp.Cargaison', to='bacsApp.bac')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bacsApp.site')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bacsApp.utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='cargaison',
            name='livraison',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bacsApp.livraison'),
        ),
    ]
