# Generated by Django 4.0.4 on 2023-07-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacsApp', '0002_alter_livraison_livraison_alter_site_bac'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='livraison',
            name='document',
            field=models.ManyToManyField(to='bacsApp.documnet'),
        ),
    ]
