# Generated by Django 4.0.4 on 2023-07-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacsApp', '0003_documnet_livraison_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documnet',
            name='url',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
