# Generated by Django 4.0.4 on 2023-08-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacsApp', '0004_alter_documnet_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='furnisseur',
        ),
        migrations.AddField(
            model_name='site',
            name='adresse',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='libelle',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
