# Generated by Django 4.0.4 on 2023-08-20 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bacsApp', '0005_remove_site_furnisseur_site_adresse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='libelle',
        ),
    ]
