# Generated by Django 4.0.4 on 2023-08-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacsApp', '0006_remove_site_libelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='mdp',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='retour',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
