# Generated by Django 4.0.4 on 2023-08-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bacsApp', '0008_rename_livraison_livraison_une_cargaison'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documnet',
            new_name='Document',
        ),
    ]
